server:
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name:Config-Default
  datasource:
    url: jdbc:mysql://localhost:3306/onlineretailstore
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
